/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/owvkmiKdCmr
 */
import Link from "next/link"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Test() {
  return (
    <div key="1" className="w-full space-y-12">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">QueerSports Space</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Resources
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Lectures
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <div
        className="space-y-8 text-center py-12 lg:py-24"
        style={{
          backgroundImage: "\"url('/placeholder.svg')\"",
        }}
      >
        <div className="space-y-2">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">QueerSports Space</h1>
          <p className="mx-auto max-w-2xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Creating an inclusive space for LGBTQ+ athletes and sports enthusiasts.
          </p>
        </div>
      </div>
      <div className="bg-gray-100/50 py-12 lg:py-24 dark:bg-gray-800/50">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">About Us</h2>
            <p className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              We are dedicated to promoting diversity and inclusion in sports. Our mission is to provide a safe and
              supportive environment for LGBTQ+ athletes and allies.
            </p>
          </div>
        </div>
      </div>
      <div className="container py-12 lg:py-24">
        <div className="grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Resources</h2>
            <p className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Access our curated collection of articles, videos, and links related to LGBTQ+ inclusion in sports.
            </p>
          </div>
        </div>
      </div>
      <div className="bg-gray-100 py-12 lg:py-24 dark:bg-gray-800">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Lectures</h2>
            <p>
              <div className="space-y-3">
                <Card className="w-full max-w-md">
                  <CardHeader>
                    <CardTitle>PDF Documents</CardTitle>
                    <CardDescription>Explore our collection of PDFs and documents.</CardDescription>
                  </CardHeader>
                  <CardContent className="grid gap-4">
                    <div className="flex items-center space-x-4">
                      <FileIcon className="h-6 w-6" />
                      <Link className="text-blue-600 hover:underline" href="#">
                        Document 1
                      </Link>
                    </div>
                    <div className="flex items-center space-x-4">
                      <FileIcon className="h-6 w-6" />
                      <Link className="text-blue-600 hover:underline" href="#">
                        Document 2
                      </Link>
                    </div>
                    <div className="flex items-center space-x-4">
                      <FileIcon className="h-6 w-6" />
                      <Link className="text-blue-600 hover:underline" href="#">
                        Document 3
                      </Link>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </p>
          </div>
        </div>
      </div>
      <div className="container py-12 lg:py-24">
        <div className="grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact Us</h2>
            <form className="grid gap-4 md:gap-6">
              <div className="w-full space-y-12">
                <header className="px-4 lg:px-6 h-14 flex items-center">
                  <Link className="flex items-center justify-center" href="#">
                    <MountainIcon className="h-6 w-6" />
                    <span className="sr-only">QueerSports Space</span>
                  </Link>
                  <nav className="ml-auto flex gap-4 sm:gap-6">
                    <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                      About
                    </Link>
                    <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                      Resources
                    </Link>
                    <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                      Lectures
                    </Link>
                    <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                      Contact
                    </Link>
                  </nav>
                </header>
                <div className="container space-y-8 text-center py-12 lg:py-24">
                  <div className="space-y-2">
                    <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">QueerSports Space</h1>
                    <p className="mx-auto max-w-2xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                      Creating an inclusive space for LGBTQ+ athletes and sports enthusiasts.
                    </p>
                  </div>
                </div>
                <div className="bg-gray-100/50 py-12 lg:py-24 dark:bg-gray-800/50">
                  <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
                    <div className="space-y-3">
                      <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">About Us</h2>
                      <p className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                        We are dedicated to promoting diversity and inclusion in sports. Our mission is to provide a
                        safe and supportive environment for LGBTQ+ athletes and allies.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="container py-12 lg:py-24">
                  <div className="grid items-center justify-center gap-4 px-4 text-center md:px-6">
                    <div className="space-y-3">
                      <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Resources</h2>
                      <p className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                        Access our curated collection of articles, videos, and links related to LGBTQ+ inclusion in
                        sports.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="bg-gray-100 py-12 lg:py-24 dark:bg-gray-800">
                  <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
                    <div className="space-y-3">
                      <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Lectures</h2>
                      <p className="mx-auto max-w-3xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                        Watch recordings or read transcripts of our past lectures and presentations on LGBTQ+ inclusion
                        in sports.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="container py-12 lg:py-24">
                  <div className="grid items-center justify-center gap-4 px-4 text-center md:px-6">
                    <div className="space-y-3">
                      <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact Us</h2>
                      <form className="grid gap-4 md:gap-6">
                        <div className="flex gap-4">
                          <Label htmlFor="name">Name</Label>
                          <Input id="name" placeholder="Enter your name" />
                        </div>
                        <div className="flex gap-4">
                          <Label htmlFor="email">Email</Label>
                          <Input id="email" placeholder="Enter your email" type="email" />
                        </div>
                        <div className="flex gap-4">
                          <Label htmlFor="message">Message</Label>
                          <Textarea className="min-h-[100px]" id="message" placeholder="Enter your message" />
                        </div>
                        <div className="flex flex-col gap-2 lg:flex-row">
                          <Button type="submit">Submit</Button>
                          <Button type="reset" variant="outline">
                            Reset
                          </Button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
                <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
                  <p className="text-xs text-gray-500 dark:text-gray-400">
                    © 2024 QueerSports Space. All rights reserved.
                  </p>
                  <nav className="sm:ml-auto flex gap-4 sm:gap-6">
                    <Link className="text-xs hover:underline underline-offset-4" href="#">
                      Terms of Service
                    </Link>
                    <Link className="text-xs hover:underline underline-offset-4" href="#">
                      Privacy
                    </Link>
                  </nav>
                </footer>
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" type="email" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="message">Message</Label>
                <Textarea className="min-h-[100px]" id="message" placeholder="Enter your message" />
              </div>
              <div className="flex flex-col gap-2 lg:flex-row">
                <Button type="submit">Submit</Button>
                <Button type="reset" variant="outline">
                  Reset
                </Button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 QueerSports Space. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}
